export const bookClubs = [
  {
    id: 1,
    name: 'Classic Book Club',
    location: 'New York',
    description: 'A book club for classic literature enthusiasts.',
    members: 25,
  },
  {
    id: 2,
    name: 'Sci-Fi & Fantasy Book Club',
    location: 'San Francisco',
    description: 'Exploring the realms of science fiction and fantasy.',
    members: 18,
  },
  {
    id: 3,
    name: 'Mystery Book Club',
    location: 'Chicago',
    description: 'Unraveling the mysteries of thrilling novels.',
    members: 12,
  },
  {
    id: 4,
    name: 'Romance Readers Club',
    location: 'Los Angeles',
    description: 'For those who adore love stories and happily-ever-afters.',
    members: 30,
  },
  {
    id: 5,
    name: 'Young Adult Book Club',
    location: 'Seattle',
    description: 'Exploring the vibrant world of young adult literature.',
    members: 22,
  },
  {
    id: 6,
    name: 'History Book Club',
    location: 'London',
    description: 'Delving into the past through captivating historical reads.',
    members: 15,
  },
  {
    id: 7,
    name: 'Thriller & Suspense Book Club',
    location: 'Boston',
    description: 'Exploring the edge-of-your-seat world of thrillers and suspense.',
    members: 17,
  },
  {
    id: 8,
    name: 'Contemporary Fiction Book Club',
    location: 'Toronto',
    description: 'Discovering the beauty of contemporary fiction works.',
    members: 20,
  },
  {
    id: 9,
    name: 'Science & Technology Book Club',
    location: 'San Diego',
    description: 'Exploring the fascinating world of science and technology.',
    members: 14,
  },
  {
    id: 10,
    name: 'Biography Book Club',
    location: 'Sydney',
    description: 'Uncovering the remarkable lives of real people through biographies.',
    members: 16,
  },
  {
    id: 11,
    name: 'Poetry Book Club',
    location: 'Paris',
    description: 'Immersing in the beauty and depth of poetry.',
    members: 10,
  },
  {
    id: 12,
    name: 'Business & Finance Book Club',
    location: 'Singapore',
    description: 'Exploring the world of business and finance through books.',
    members: 19,
  },
  {
    id: 13,
    name: 'Self-Help Book Club',
    location: 'Melbourne',
    description: 'Empowering individuals through self-help and personal development books.',
    members: 13,
  },
  {
    id: 14,
    name: 'Graphic Novel Book Club',
    location: 'Chicago',
    description: 'Discovering the artistry and storytelling of graphic novels.',
    members: 16,
  },
  {
    id: 15,
    name: 'Cookbook Club',
    location: 'New York',
    description: 'Exploring the culinary world through cookbooks and sharing recipes.',
    members: 24,
  },
  {
    id: 16,
    name: 'Travel Book Club',
    location: 'London',
    description: 'Embarking on literary journeys to different parts of the world.',
    members: 11,
  },
  {
    id: 17,
    name: 'Dystopian Fiction Book Club',
    location: 'Berlin',
    description: 'Exploring dystopian worlds through thought-provoking fiction.',
    members: 14,
  },
  {
    id: 18,
    name: 'Art & Design Book Club',
    location: 'New York',
    description: 'Appreciating art and design through insightful books.',
    members: 18,
  },
  {
    id: 19,
    name: 'Nature & Environment Book Club',
    location: 'Vancouver',
    description: 'Exploring the wonders of nature and environmental issues.',
    members: 13,
  },
  {
    id: 20,
    name: 'Psychological Thriller Book Club',
    location: 'Los Angeles',
    description: 'Delving into the complex minds and psychological twists of thrilling reads.',
    members: 15,
  },
  {
    id: 21,
    name: 'Fantasy Adventure Book Club',
    location: 'Seattle',
    description: 'Embarking on epic fantasy adventures through captivating novels.',
    members: 21,
  },
  {
    id: 22,
    name: 'True Crime Book Club',
    location: 'London',
    description: 'Exploring the dark realm of true crime stories.',
    members: 17,
  },
  {
    id: 23,
    name: 'Literary Fiction Book Club',
    location: 'New York',
    description: 'Discovering the artistry and depth of literary fiction.',
    members: 23,
  },
  {
    id: 24,
    name: 'Health & Wellness Book Club',
    location: 'Sydney',
    description: 'Exploring books that promote health, wellness, and mindfulness.',
    members: 12,
  },
  {
    id: 25,
    name: 'Children\'s Book Club',
    location: 'Toronto',
    description: 'Inspiring young readers through engaging and educational children\'s books.',
    members: 28,
  },
];
