export const bookClubs = [
  {
    id: 1,
    name: 'Classic Book Club',
    location: 'New York',
    description: 'A book club for classic literature enthusiasts.',
    members: 25,
  },
  {
    id: 2,
    name: 'Sci-Fi & Fantasy Book Club',
    location: 'San Francisco',
    description: 'Exploring the realms of science fiction and fantasy.',
    members: 18,
  },
  {
    id: 3,
    name: 'Mystery Book Club',
    location: 'Chicago',
    description: 'Unraveling the mysteries of thrilling novels.',
    members: 12,
  },
  {
    id: 4,
    name: 'Romance Readers Club',
    location: 'Los Angeles',
    description: 'For those who adore love stories and happily-ever-afters.',
    members: 30,
  },
  {
    id: 5,
    name: 'Young Adult Book Club',
    location: 'Seattle',
    description: 'Exploring the vibrant world of young adult literature.',
    members: 22,
  },
  {
    id: 6,
    name: 'History Book Club',
    location: 'London',
    description: 'Delving into the past through captivating historical reads.',
    members: 15,
  },
  {
    id: 7,
    name: 'Thriller & Suspense Book Club',
    location: 'Boston',
    description: 'Exploring the edge-of-your-seat world of thrillers and suspense.',
    members: 17,
  },
  {
    id: 8,
    name: 'Contemporary Fiction Book Club',
    location: 'Toronto',
    description: 'Discovering the beauty of contemporary fiction works.',
    members: 20,
  },
  {
    id: 9,
    name: 'Science & Technology Book Club',
    location: 'San Diego',
    description: 'Exploring the fascinating world of science and technology.',
    members: 14,
  },
  {
    id: 10,
    name: 'Biography Book Club',
    location: 'Sydney',
    description: 'Uncovering the remarkable lives of real people through biographies.',
    members: 16,
  },
  {
    id: 11,
    name: 'Poetry Book Club',
    location: 'Paris',
    description: 'Immersing in the beauty and depth of poetry.',
    members: 10,
  },
  {
    id: 12,
    name: 'Business & Finance Book Club',
    location: 'Singapore',
    description: 'Exploring the world of business and finance through books.',
    members: 19,
  },
  {
    id: 13,
    name: 'Self-Help Book Club',
    location: 'Melbourne',
    description: 'Empowering individuals through self-help and personal development books.',
    members: 13,
  },
  {
    id: 14,
    name: 'Graphic Novel Book Club',
    location: 'Chicago',
    description: 'Discovering the artistry and storytelling of graphic novels.',
    members: 16,
  },
  {
    id: 15,
    name: 'Cookbook Club',
    location: 'New York',
    description: 'Exploring the culinary world through cookbooks and sharing recipes.',
    members: 24,
  },
  {
    id: 16,
    name: 'Travel Book Club',
    location: 'London',
    description: 'Embarking on literary journeys to different parts of the world.',
    members: 11,
  },
  {
    id: 17,
    name: 'Dystopian Fiction Book Club',
    location: 'Berlin',
    description: 'Exploring dystopian worlds through thought-provoking fiction.',
    members: 14,
  },
  {
    id: 18,
    name: 'Art & Design Book Club',
    location: 'New York',
    description: 'Appreciating art and design through insightful books.',
    members: 18,
  },
  {
    id: 19,
    name: 'Nature & Environment Book Club',
    location: 'Vancouver',
    description: 'Exploring the wonders of nature and environmental issues.',
    members: 13,
  },
  {
    id: 20,
    name: 'Psychological Thriller Book Club',
    location: 'Los Angeles',
    description: 'Delving into the complex minds and psychological twists of thrilling reads.',
    members: 15,
  },
  {
    id: 21,
    name: 'Fantasy Adventure Book Club',
    location: 'Seattle',
    description: 'Embarking on epic fantasy adventures through captivating novels.',
    members: 21,
  },
  {
    id: 22,
    name: 'True Crime Book Club',
    location: 'London',
    description: 'Exploring the dark realm of true crime stories.',
    members: 17,
  },
  {
    id: 23,
    name: 'Literary Fiction Book Club',
    location: 'New York',
    description: 'Discovering the artistry and depth of literary fiction.',
    members: 23,
  },
  {
    id: 24,
    name: 'Health & Wellness Book Club',
    location: 'Sydney',
    description: 'Exploring books that promote health, wellness, and mindfulness.',
    members: 12,
  },
  {
    id: 25,
    name: 'Children\'s Book Club',
    location: 'Toronto',
    description: 'Inspiring young readers through engaging and educational children\'s books.',
    members: 28,
  },
];

export const recommendedBooks = [
  {
    id: 1,
    title: '1000 Years of Joys and Sorrows',
    author: 'Ai Weiwei',
    genre: 'Genre 1',
    rating: 4.5,
    image: 'https://api.time.com/wp-content/uploads/2021/11/100-best-books-1000-years-of-joys-and-sorrors.jpg?quality=85&w=600&h=600&crop=1',
  },
  {
    id: 2,
    title: 'Afterparties',
    author: 'Anthony Veasna So',
    genre: 'Genre 2',
    rating: 4.2,
    image: 'https://api.time.com/wp-content/uploads/2021/11/100-best-books-afterparties.jpg?quality=85&w=600&h=600&crop=1',
  },
  {
    id: 2,
    title: 'Cloud Cuckoo Land',
    author: 'Anthony Doerr',
    genre: 'Genre 2',
    rating: 4.0,
    image: 'https://api.time.com/wp-content/uploads/2021/11/100-best-books-code-breaker.jpg?quality=85&w=600&h=600&crop=1',
  },
];

export const upcomingEvents = [
  {
    id: 1,
    title: 'Marvels Event',
    date: 'June 15, 2023',
    time: '6:00 PM',
    location: 'New York',
    description: '2022 is shaping up to be a big year for exciting Marvel events. Chip Zdarsky is leading the Devil’s Reign event that shifted the paradigm in a big way for Daredevil, Kingpin, and Elektra beginning last year. It will end with an “Omega” issue in May.',
    image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpaperaccess.com%2Ffull%2F342047.jpg&f=1&nofb=1&ipt=2bcfc73b97335751316f4989dc2e6422f55943dcb72ae43f5bf04f09d02b9019&ipo=images',
  },
  {
    id: 2,
    title: 'DC Event',
    date: 'June 20, 2023',
    time: '7:30 PM',
    location: 'London',
    description: 'Atomic robots, alien worlds, mad scientists, sinister curses, and villains from throughout the DC Universe—welcome to the wild adventures of Billy Batson, whose big red alter ego defends the Earth from its weirdest and wildest threats!',
    image:'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fattackofthefanboy.com%2Fwp-content%2Fuploads%2F2016%2F01%2Fdc-universe-online.jpg&f=1&nofb=1&ipt=9ff31295b5e883a7f7046bdc6270ad8f576fac7a483fe9bac8c3817783447b24&ipo=images'
  },
];